services:
  backend:
    build: ./backend
    ports:
      - "8000:80" # Host 8000 -> contenedor 80
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: challenge-matrice
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:80" # Host 3001 -> contenedor 80

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge-matrice
    ports:
      - "3308:3306" # Host 3308 -> contenedor 3306
